classDiagram
    class DisplayBoard {
        +String: id
        +String: title
        +String: content
        +startDate: Date
        +endDate: Date
        +status: String
        +getStatus(): String
    }

    class Admin {
        +String id
        +String name
        +String email
        +manageBoard(DisplayBoard)
    }

    class System {
        +List~DisplayBoard~ boards
        +createBoard(title: String, content: String)
        +updateBoard(id: String, newTitle: String, newContent: String)
        +deleteBoard(id: String)
        +listBoards()
    }

    Admin --> System : "uses"
    System --> DisplayBoard : "manages"