@startuml
left to right direction
actor "Trainer" as fc
actor "Trainee" as fa
rectangle DisplayBoard {
  usecase "Update" as UC1
  usecase "Add" as UC2
  usecase "Display" as UC3
}
fc -- UC1
fc -- UC2
fc -- UC3
fa -- UC3
@enduml